version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-teste
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: